name: 'Setup environment'
description: 'Setup test environment'

runs:
  using: "composite"
  steps:  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16, 18)'
    
